name: generate animation

on:
  schedule: # 매일 자정에 실행
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ampersandor
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 